name: Build and Release
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  eslint:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
         
      - name: Install Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
         version: latest
         run_install: true

      - name: Build
        run: pnpm build

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            prerelease: false
            files: |
                LICENSE.txt
                built/